language: node_js
node_js:
- 10
services:
- docker
env:
  global:
  - REACT_APP_API_BASE_URL=http://localhost:8080
  - PACT_BROKER_BASE_URL=https://conventicgmbh.pact.dius.com.au
  # PACT_BROKER_TOKEN is encrypted below
  - secure: "KZHbV9eIKns6aTL2PaHajGCxK2DSlsUppAAw1BYvPINWDGMnTfrHu0zrrOhg5lK5d6kAx75u4nS21KGDCMiFVsmmTHLxGd97w2gPHwo8KXOJZZgjbuO0bmThs1hylOWNdUY6VA8pAKTmZ/5FdoVpjpVuFzyFE5t0B4i/x8HJpsy+QTspLvLyjmfYZakd0LC9SSSBL/5JQNiwLQ+XGoDBwTm1dQm/zaY43vVmu39y2AJWId7XXA9wk0d5h2smA/pboVQwE9gc6V3O/yuxVl0yo/AH4NATfFzZAtOw5negRL5bqnC78n5LOQI9931G/2O0qTnD3pp6bZiOlftSul3YMsqv4wPHCVRHqBB5X55MxqoI+zMvU40fKbdOdh2Hj1bJdIavMUF5rkAngWup2Njyk+HKrnxG7CMWJBrVa0V0HDXJ4BBqmnJfR6Y4s43rH63M3ifwnYMzmVXxYjHVeTXIs2acqzJHQ/b7fZl3W88XYb2Uli4+LqEiN4tXwnXsy0ytrDxnFnzdaQ3y8wTri2IDi4KIRfz/SA/JjUQeK1PQp1rI7Zo+6KsYqsW9UyFFREUKF3N/SOpWlvlhiNELEO8dNUHyYMemj/TElSBXRbRUMyugrfph3pSIJdpaD7z9wYdc6za1PcedHFbBMysd7FFig4kBRHpZaFiX285goQdDRdY="
before_script:
  - docker pull pactfoundation/pact-cli:latest
script:
- make ci
