language: node_js
node_js:
- 10
services:
- docker
env:
  global:
  - REACT_APP_API_BASE_URL=http://localhost:8080
  - PACT_BROKER_BASE_URL=https://conventicgmbh.pact.dius.com.au
  # PACT_BROKER_TOKEN is encrypted below
  - secure: "GEH2V+/b5ehp0VJ0btvoexCaFXbKhV1OlTbJkQLZBw8HT6cZFY5UIYHrxwEV3luMdnmO85kJM6914z23Xqq9iAoe8b+MgBunq4HOFy2O9AOQgxc4Lmjvx3q1dPl3AJ7+NIEdVyXy0amFhbdXANidch3f0T0/CoA4sRmPZYWRys1TlcCmomAew95tROXXXS/M6Sztw5eSnnMz2IBedxArcj7ktfaaeA1/D/Fleo6MyAynmHaycFRq1FjyWOy06e84uJzpenc3gNGnbjvHA+j89rbNJ8lQtcoxmAXRiFyv+U2hbeFUu+nOcGYx6S6t87WzRD2P/TaslPyUkCLmbtsYjHhqhODlbdqI0lSUQop8sszYlWvWnjvNeoZhsBLbw2wIB6Z5SjsucgsmT7Ixjf3kTOTG4JjBNV5dkPothLZu7k01nWquKZJr1GXzF9RFEm5vn7kO85wIVLV9X7fEOdKF0ONWXSYeKPI1AwQyW1318hmf4LUF8KVmJvzJiKb9cvQTg+6V+/XrZI9ahPyQdcvDmRYs5pCHir+Y3pWKCjLm0dAFxhUFGVsVblisH7NfSv5+EyRS7roQYWM0IMbg0+0GCfzFkeMAQQk2jNhNt8NoIbdHooLbi0jbGJaplo9m9O3hT4nKi6tZ8u3y8XF+5l7XEO8bFWgAfFdsMWikbIZV6zw="
before_script:
  - docker pull pactfoundation/pact-cli:latest
script:
- make ci
